### DISCUSSION TITLE
Allow setting kcat configuration directly from environment variable

### DISCUSSION THREAD

**Discussion by SoerenHenning** [edenhill/kafkacat#366] [Ideas]
According to the [Readme](https://github.com/edenhill/kcat#configuration), it is currently possible to specific an environment variable `KCAT_CONFIG`, which specifies the path to a file in which a [configuration](https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md) can be found.

It would be nice, if we were able to set the configuration directly as environment variable. Especially CI pipelines or Docker Compose testing setups could be simplified, we would not need to write the config to a file first. An example for Docker Compose could look like this:

```yaml
version: '2.2'
services:
  kcat:
    image: edenhill/kcat:1.7.1
    environment:
      KCAT_CONFIG: | # This is not possible at the moment
        metadata.broker.list=kafka:9092
```

Setting configuration options this way is, for example, possible with Apache Flink.
